project:
  type: book

book:
  title: R in Production
  author: Hadley Wickham
  chapters:
    - index.qmd
    - introduction.qmd
    - whole-game.qmd
    - project-life.qmd

    - part: another-machine.qmd
      chapters:
      - github-actions.qmd
      - paper-cuts.qmd
      - packages.qmd
      - debugging.qmd
      - logging.qmd
      - auth.qmd

    - part: multiple-times.qmd
      chapters:
      - schema.qmd
      - packages-platform.qmd
      - universe.qmd
      - requirements.qmd

    - part: shared-responsibility.qmd
      chapters:
      - parquet.qmd
      - team-conventions.qmd
      - code-review.qmd
