project:
  type: book

book:
  title: R in Production
  author: Hadley Wickham

  reader-mode: true

  site-url: https://r-in-production.org/
  repo-url: https://github.com/hadley/r-in-production/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - introduction.qmd
    - whole-game.qmd
    - project-life.qmd

    - part: another-machine.qmd
      chapters:
      - github-actions.qmd
      - paper-cuts.qmd
      - packages.qmd
      - debugging.qmd
      - logging.qmd
      - auth.qmd

    - part: multiple-times.qmd
      chapters:
      - schema.qmd
      - packages-platform.qmd
      - universe.qmd
      - requirements.qmd

    - part: shared-responsibility.qmd
      chapters:
      - parquet.qmd
      - team-conventions.qmd
      - code-review.qmd

format:
  html:
    theme:
      - cosmo
      - r-in-production.scss
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple
