project:
  type: book

book:
  title: R in Production
  author: Hadley Wickham
  chapters:
    - index.qmd
    - introduction.qmd

    - part: another-machine.qmd
      chapters:
      - packages.qmd
